version: '3.8'

services:
    backend:
        image: back_app
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
        container_name: backend
    frontend:
        image: front_app
        ports:
            - 5000:5000
        container_name: frontend
    redis:
        image: redis:alpine
        container_name: redis
