version: '3.8'

services:
    backend:
        image: back_app
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
        depends_on:
            - db
            - redis
        container_name: backend
        
    frontend:
        image: front_app
        ports:
            - 5000:5000
        container_name: frontend
        
    redis:
        image: redis:alpine
        container_name: redis
        
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: postgres
        container_name: db_app
        volumes:
          - ./database:/var/lib/postgresql/data
          
    nginx:
        image: nginx:alpine
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on:
             - backend
             - frontend
        container_name: nginx
